account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  #  url(r'^login/$', views.user_login, name='login'),
  url(r'^login/$', 'django.contrib.auth.views.login',name='login'),
  url(r'^logout/$', 'django.contrib.auth.views.logout',name='logout'),
  url(r'^logout-then-login/$', 'django.contrib.auth.views.logout_then_login',name='logout_then_login'),
  url(r'^$',views.dashboard, name='dashboard'),
]

fotoworld/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static 



urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^news/', include('news.urls', namespace='news', app_name='news')),
    url(r'^account/', include('account.urls',
                              namespace='account', app_name='account')),

    url(r'^images/', include('images.urls', namespace='images', app_name='images')),
    url(r'^$', TemplateView.as_view(template_name='home/index.html'), name="homr"),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),

]

templates/base.html
{% load staticfiles %}
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Foto World</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Font awesome -->
    <link rel="stylesheet" href="lib/font-awesome.min.css">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat&amp;subset=latin-ext" rel="stylesheet">



    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
        crossorigin="anonymous">

    <!-- My Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    <div class='header'>
        <div class='menu'>
            <div class="container">
                <ul class="list-menu">
                    <li>
                        <a href="/images">Home</a>
                    </li>
                    <li>
                        <a href="/news">News</a>
                    </li>

                    <span class="user">
                        {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'account:dashboard' %}">
                                <span style="color:white;">
                                    {{request.user.first_name}}</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'account:logout' %}"> Logout</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'account:login' %}"> Login</a>
                        </li> {% endif %}
                    </span>
                    <!-- <a href="/account/login">Sign in</a> -->
                </ul>
            </div>
        </div>

    </div>
    <div class='logo'>
        <div class="container">
            <h1>FotoWorld</h1>
        </div>
    </div>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
    </div>
    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>


    <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method))
        }
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.typoe) && !this.crossDomian) {
                    xhr.setRequestheader("X-CSRFToken", csrftoken)
                }
            }
        });
        $(document).ready(function () {
            {% block domready %}
            {% endblock %}
        });

    </script>
</body>

templates/pagination.html
<div class='pagination'>
    <span class='step-links'>
        {% if page.has_previous%}
        <a href="?page={{page.previous_page_number}}">Cofnij</a>
        {% endif %}
   
    <span class='current'>
       strona {{page.number}} z {{page.paginator.num_pages}}
        </span>
        {% if page.has_next %}
        <a href="?page={{page.next_page_number}}">Dalej</a>
        {% endif %}
    </span>
</div>